DROP TABLE IF EXISTS code;

CREATE TABLE code(
    id SERIAL PRIMARY KEY,
    email VARCHAR REFERENCES users(email) NOT NULL UNIQUE,
    code VARCHAR NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
